### ISSUE TITLE
NullReferenceException when running under net6.0 

### ISSUE THREAD

**Issue by ruiminwang** [microsoft/Trill#165]
We got the following exceptions when running ASA (who used Trill as computing engine) with net6.0 locally.

[Error] 7/25/2022 10:26:18 AM : **System Exception** Object reference not set to an instance of an object.
[Error] 7/25/2022 10:26:18 AM :    at Microsoft.StreamProcessing.Internal.FastDictionaryGenerator.CreateFastDictionaryGenerator[TKey,TValue](IEqualityComparerExpression`1 comparerExp, Int32 capacity, Func`3 equalsFunc, Func`2 getHashCodeFunc, QueryContainer container)
   at Microsoft.StreamProcessing.SnapshotWindowTumblingPipe`4..ctor(SnapshotWindowStreamable`4 stream, IStreamObserver`2 observer, Int64 hop)
   at Microsoft.StreamProcessing.SnapshotWindowStreamable`4.CreateTumbling(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.SnapshotWindowStreamable`4.CreatePipe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UnaryStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.MulticastStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UngroupStreamable`4.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.MultiUnionStreamable`2.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UnaryStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UnaryStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UnaryStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UnaryStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UnaryStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UnaryStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.UnaryStreamable`3.Subscribe(IStreamObserver`2 observer)
   at Microsoft.StreamProcessing.IO.RecordEventObservable.Subscribe(IObserver`1 observer)
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, ICheckpointReader checkpointReader)
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.RestoreInternal(ICheckpointReader checkpointReader, AnchorData anchor)
   at Microsoft.Streaming.Processors.Compute.BaseComputeContainer`2.Restore(ICheckpointReader checkpointReader, AnchorData anchorData)
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync()

**Comment by ruiminwang** [comment]
sorry, we didn't reference the newest code. It's already resolved in #155 .
